server:
  port: 8081

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/FlowerTea_System?characterEncoding=utf8

logging:
  file:
    name: FlowerTea.log
    path: D:\FlowerTea
